
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Fallback para `prisma generate` en CI/Vercel (no conecta a la BD real).
    url: process.env.DATABASE_URL ?? "file:./prisma/dev.db",
  },
});
